module.exports={
    devServer:{
        proxy:{
            "/ygsx":{
                "target":"http://localhost:3000",
                "changeOrigin":true,
                "pathRewrite":{
                    "^/ygsx":"/"
                }
            }
        }
    }
}